- README.md
We should probably be writing this to stderr rather than stdout, so
wanted to change the example so people don't accidentally log to stdout.
> Use console.error instead of console.log in examples

- README.md
- index.js
- package.json
Earlier logger module was not being exported resulting in errors if you followed the directions on how to import it.
This change exports the logger module as an attribute of the exported object.
Made a patch bump since the previous one really didn't work.
Tested:
`make build` correctly creates `lib-js/logger/logger.js`.
> Fix logger export

- Makefile
- index.js
- lib/kayvee.ts
- lib/logger/logger.ts
- package.json
- test/kayvee.ts
- test/logger_test.ts
Add dev-dependency: eslint-airbnb-dev
Right now linting is NOT enforced in tests. Should it always run? 
There are a lot of linting errors that would need to be fixed first, so I could try to address those in this PR or provide a workaround like making sure the number of linting errors doesn't increase.
> Linting improvements

- README.md
- lib/middleware.ts
- test/middleware.ts
Previously, we weren't logging `source`, `title`, or `level`. Now we are. `level` is determined based on the response's status code.
`source` is passed by the user among the config `options`.
It's a required field.
Updated title: `request-finished`
> Infra 1595 middleware fixes

- lib/kayvee.ts
- lib/logger/logger.ts
- package.json
- test/logger_test.ts
* if clients send an object that is reused in other contexts they would have additional properties.
> clone input data before modifying

- lib/kayvee.ts
- test/kayvee.ts
So that kayvee logs can include the deploy environment automatically (needed for metrics to distinguish on env)
> inject deploy env to kayvee logs

- README.md
- lib/middleware.ts
- package.json
- test/middleware.ts
* allows different mount points for the directory
* only applies to files in the path
* only skips if statusCode > 399
* refactor so that the logger initialization only happens on startup
_testing_
* tested by installing this in oauth and running locally.
```bash
$ curl http://localhost:5000/images/loader.gi
$ curl http://localhost:5000/images/loader.gif
$ curl http://localhost:5000/
[github:clever/oauth]	 KayveeMiddleware: Skipping successful requests for files in /home/mohit/git-clever/oauth/public at /
[github:clever/oauth]	 {"method":"GET","path":"/images/loader.gi","params":"","response-size":2132,"response-time":176168819,"status-code":404,"ip":"::ffff:127.0.0.1","via":"kayvee-middleware","level":"info","title":"request-finished","source":"oauth"}
[github:clever/oauth] …
```
> add option to skip static requests for a directory

- lib/middleware.ts
- test/middleware.ts
This helps us distinguish canary service metrics from non-canary metrics
> INFRA-1956: Add canary flag

- lib/router/index.ts
- lib/router/schema_definitions.json
- test/router.ts
The following errors should now be found:
- Top level prop is "route" instead of "routes"
- A rule has a "$", "%", "{", or "}"
- A rule has "match" instead of "matches"
- A rule has "outputs" instead of "output"
Also re-syncs json-schema with kayvee-go
> Refactor json-schema to validate a full kv-config object

- lib/router/index.ts
This information is redundant with `container_app`.
> Removed app-name from kayvee meta data

- lib/router/index.ts
- test/router.ts
A number of existing rules have `!= NIL` matches.  We don't want to add support for a `not` operator in log-routing (unclear about syntax and has significant performance and safety ramifications), so it seemed most natural to add `*` which means it'll match anything.  If `*` is used in a matcher, no other values can be specified.
Added support for bools because a number of rules look for booleans and because a number of well-entrenched bool flags already exist (ex: canary, signaled, is_paid, is_demo).
> Added support for wildcard and bool matching

- lib/router/schema_definitions.json
- package.json
- test/router.ts
It refers to a field that contains the value that'll be sent to the output.  Useful when a log multiple line contains values to alert on.
cc @nathanleiby
> Added support for value overrides

- README.md
- lib/logger/logger.ts
- lib/middleware.ts
- package.json
- test/kvconfig.yml
- test/middleware.ts
It turns out kayvee-middleware doesn't use kayvee-logger.  As a result it by passes log-routing which is surprising and inconsistent with kayvee-go.
> Made kv-middleware respect log-routing

- README.md
- lib/logger/logger.ts
- package.json
- test/kvconfig.yml
- test/logger_test.ts
previously, just counted the number of logs that matched each rule.
also, adds test coverage.
> logger: update mockRouter to return route data

- lib/router/index.ts
- lib/router/schema_definitions.json
- test/router.ts
Previously alert outputs didn't specify a `value_field` attribute.  This was an issue because the kvmeta filter in log-router expected it to be there.  Adding it should fix log-routing alerts.
Additionally, this PR makes `value_field` an optional field for both metrics and alerts outputs.  When not specified `value_field` defaults to `value`, which means by default the quality specified in `value` property of the matched log line will be sent to signalfx as the time-series's datapoint.
Related:
https://github.com/Clever/log-router/pull/80
https://clever.atlassian.net/browse/INFRA-2133
cc @nathanleiby, @ahsojar
> Made value_field an optional setting on metrics and alerts outputs

- lib/router/schema_definitions.json
- package.json
- test/router.ts
Currently, it's an error to write an alert without dimensions.
Related:
- https://github.com/Clever/turk-herder/pull/47
- https://github.com/Clever/kayvee-go/pull/50
> Allow empty dimensions fields on alerts

- lib/router/schema_definitions.json
- package.json
- test/router.ts
allow injecting the channel name in notifications from another kv field
disable support for getting channel name from an env var
Issue: https://clever.atlassian.net/browse/INFRA-2202
Related kayvee-go PR: https://github.com/Clever/kayvee-go/pull/53
> router: allow kvsubst for channel name in notifications

- lib/logger/logger.ts
- package.json
- test/kvconfig.yml
- test/logger_test.ts
context: https://basarat.gitbooks.io/typescript/docs/arrow-functions.html#tip-arrow-functions-with-libraries-that-use-this
> fix mock logger to have access to globals

- Makefile
- lib/kayvee.ts
- lib/logger/logger.ts
- package.json
- test/kayvee.ts
- test/logger_test.ts
- test/middleware.ts
Similar to how _DEPLOY_ENV works, kayvee will add a parameter called `workflow_id` to every log if there's env-var called _EXECUTION_NAME.
Jira: https://clever.atlassian.net/browse/INFRA-2526
> Added support for workflow_id/_EXECUTION_NAME

- lib/kayvee.ts
- lib/logger/logger.ts
**Overview:**: https://clever.atlassian.net/browse/INFRA-3363
The multipod deploy backend in catapult adds a few new environment variables that will be useful when searching logs: the pod ID, the AWS region, and the AWS account where the pod is running. This PR changes kayvee to log these values.
> instrument logs with pod info

- package.json
It looks like this repository has been renamed and the `package.json` file does not reflect that name change. Is that correct?
> Update GitHub URLs in package.json

- lib/middleware.ts
- package-lock.json
- package.json
- test/middleware.ts
Flare-1008
This adds query parameter name sanitization based on `qs` library's `allowPrototypes : false` option that is resistant to prototype pollution attack. More on `qs`: https://github.com/ljharb/qs/pull/98 and https://github.com/ljharb/qs/issues/200.
More on the attack: https://github.com/HoLyVieR/prototype-pollution-nsec18
> Sanitize query params before logging

- lib/middleware.ts
- package-lock.json
- package.json
- test/middleware.ts
**Overview:**
https://github.com/Clever/fluent-bit-sidecar/pull/14 starts adding canary as a tag to datadog so we don't need to set it via kv.
> remove canary field as it should be set via datadog tags
